spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5435/trading_bot
    username: trading_bot
    password: trading_bot
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:6219525923:AAF0OQFG_T2Xm-p_p_bsMdynKs4yXnHrXnE}
    username: ${TELEGRAM_BOT_USERNAME:BombersHomeBot}

server:
  port: 8080